site_name: 🌐 Building Your First API with Django and Django Rest Framework
nav:
- Home: index.md
- About: about.md
- Bonus Content: bonus.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: light blue
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: light blue
      accent: cyan

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lipemorais
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/felipedemorais_
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/felipe-de-morais/

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: |
  (CC BY-NC-SA) 2024 <a href="https://github.com/lipemorais/"  target="_blank" rel="noopener">Felipe de Morais</a>
